### ISSUE TITLE
flag provided but not defined: -distribution-id

### ISSUE THREAD

**Issue by mateus-batista** [bep/s3deploy#56]
I'm getting the error `flag provided but not defined: -distribution-id` in the last few weeks on my CircleCI builds, even though there is no new release.

This is the command running: 
`
s3deploy -source=out/ -region=us-east-1 -key=$AWS_ACCESS_KEY_ID -secret=$AWS_SECRET_ACCESS_KEY -distribution-id=$PRODUCTION_AWS_CLOUDFRONT_DISTRIBUTION_ID -bucket=$PRODUCTION_BUCKET_NAME
`

**Comment by bep** [comment]
I'm guessing here, but I assume that you build from source? Then I suspect the reason is that you build without Go Modules and that you have discovered a breaking change/bug in an upstream library.

I will keep this issue open to see what happened upstream, but you should be able to either

1. Use one of the release binaries
2. Build with a more recent Go version or build with `GO111MODULE=on`

**Comment by mateus-batista** [comment]
Hi bep, thanks for the quick response,

I'm using a step on a CircleCI build just like this: `run: go get -v github.com/bep/s3deploy`

I believe that I can specify a version with `run: go get -v github.com/bep/s3deploy@v2.3.5`

Sorry for the noob questions, I'm a little bit new to this

**Comment by bep** [comment]
No problem.

If you run

```
GO111MODULE=on go get -v github.com/bep/s3deploy
```

Note that the above should be the default behaviour from Go 1.15, so I'm little bit surprised.


You should get the latest tagged version. 

```
go get -v github.com/bep/s3deploy@v2.3.5
```

Only works for >= Go 1.16.

**Comment by mateus-batista** [comment]
Hi bep,

I was able to solve the problem by specifying the golang version from the image I was using:

```
    docker:
      - image: circleci/golang:1.15.8
```

Thanks so much for your help, I'm closing the issue.
